name: Build opencart3 and prestashop modules
on:
  push:
    branches:
      - main
jobs:
  build-addons:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get Tag
        run: echo "TAG=$(date +'%Y-%m-%d')_$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

      - name: Get filename for prestashop
        run: echo "PSS=ps_dotpayment_$TAG.zip" >> $GITHUB_ENV
      - name: Run make_zip script file for Prestashop
        run: ./make_zip.sh prestashop_release/prestashop.txt prestashop_release/ps_dotpayment $PSS

      - name: Get filename for opencart3
        run: echo "OC3=polkadot-opencart3_$TAG.ocmod.zip" >> $GITHUB_ENV
      - name: Run make_zip script file for Opencart3
        run: ./make_zip.sh opencart3_release/opencart3.txt opencart3_release/src $OC3

      - name: Get filename for woocommerce
        run: echo "WOO=woocommerce_$TAG.zip" >> $GITHUB_ENV
      - name: Run make_zip script file for WooCommerce
        run: ./make_zip.sh woocommerce_release/woocommerce.txt woocommerce_release/polkadot-payments-woocommerce $WOO

      - name: release
        run: gh release create -d $TAG $PSS $OC3 $WOO --generate-notes
