name: Build opencart3 and prestashop modules
on:
  push:
    branches:
      - main
jobs:
  build-addons:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get Tag
        run: echo "TAG=$(date +'%Y-%m-%d')_$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
      - name: Get filename for prestashop
        run: echo "PSS=ps_dotpayment_$TAG.zip" >> $GITHUB_ENV
      - name: Run make_zip script file for Prestashop
        working-directory: ./prestashop_release
        run: ./make_zip.sh $PSS
      - name: Get filename for opencart3
        run: echo "OC3=polkadot-opencart3_$TAG.ocmod.zip" >> $GITHUB_ENV
      - name: Run make_zip script file for Opencart3
        working-directory: ./opencart3_release
        run: ./make_zip.sh $OC3
      - name: release
        run: gh release create -d $TAG ./prestashop_release/$PSS ./opencart3_release/$OC3 --generate-notes
